In [11]:
def manhattan_distance(cs,fs,num):
    csarr=[]
    fsarr=[]
    for i in range(3):
        for j in range(3):
            if(cs[i][j]==num):
                csarr=[i,j]
            if(fs[i][j]==num):
                fsarr=[i,j]

    distance=abs(csarr[0]-fsarr[0])+abs(csarr[1]-fsarr[1])
    return distance

In [12]:
cs=[[1,2,3],[0,4,6],[7,5,8]]
fs=[[1,2,3],[4,5,6],[7,8,0]]

In [13]:
manhattan_distance(cs,fs,2)

0

In [14]:
def possible_routes(cs):
    z_arr=[]
    for i in range(3):
        for j in range(3):
            if(cs[i][j]==0):
                z_arr=[i,j]
                break
    poss_routes=[]
#     up
    if((z_arr[0]-1)>=0):
        poss_routes.append([z_arr[0]-1,z_arr[1]])
#     down
    if(z_arr[0]+1<3):
        poss_routes.append([z_arr[0]+1,z_arr[1]])
#         right
    if(z_arr[1]+1<3):
        poss_routes.append([z_arr[0],z_arr[1]+1])
#         left
    if(z_arr[1]-1>=0):
        poss_routes.append([z_arr[0],z_arr[1]-1])
    return poss_routes,z_arr

In [15]:
possible_routes(cs)

([[0, 0], [2, 0], [1, 1]], [1, 0])

In [16]:
import numpy as np
def solve():
    global cs
    global fs
    move=0
    while(cs!=fs):
        poss_routes,z_arr=possible_routes(cs)
        curr_manhattan_distance=100000
        best_move=[]
        for i in poss_routes:
            cs[i[0]][i[1]],cs[z_arr[0]][z_arr[1]]=cs[z_arr[0]][z_arr[1]],cs[i[0]][i[1]]
            sum_manhattan_distance=0
            for j in range(3):
                for k in range(3):
                    if(cs[j][k]!=0):
                        sum_manhattan_distance+=manhattan_distance(cs,fs,cs[j][k])
            if(sum_manhattan_distance<curr_manhattan_distance):
                curr_manhattan_distance=sum_manhattan_distance
                best_move=i
            cs[i[0]][i[1]],cs[z_arr[0]][z_arr[1]]=cs[z_arr[0]][z_arr[1]],cs[i[0]][i[1]]
        cs[best_move[0]][best_move[1]],cs[z_arr[0]][z_arr[1]]=cs[z_arr[0]][z_arr[1]],cs[best_move[0]][best_move[1]]
        move+=1
        print(np.array(cs))
    print(f'total moves: {move}')

In [17]:
solve()

[[1 2 3]
 [4 0 6]
 [7 5 8]]
[[1 2 3]
 [4 5 6]
 [7 0 8]]
[[1 2 3]
 [4 5 6]
 [7 8 0]]
total moves: 3


In [18]:
import numpy as np
np.array(cs)


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 0]])