In [2]:
import numpy as np

In [3]:
board=np.zeros((8,8))

In [4]:
board

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [5]:
import sys
board=np.zeros((5,5))
col=0
print(f'board: \n {board} ')
def check_clash():
    global board
    n=len(board)
    for i in range(n):
        for j in range(n):
            if(board[i][j]==1):
                for k in range(n):
                    if(k!=i):
                        if(board[k][j]==1):
                            return True
                    if(k!=j):
                        if(board[i][k]==1):
                            return True
                    if(i==j and j!=k):
                        if(board[k][k]==1):
                            return True
                    if(i==(n-1-j) and i!=k):
                        if(board[k][n-1-k]==1):
                            return True
    return False

def verify_output(matrix):
    rows=len(matrix)
    if(rows==0):
        return True
    arr=[]
    for i in range(rows):
        x=-1
        for j in range(rows):
            if(matrix[i][j]==1):
                if(x!=-1):
                    return False
                x=j
        if(x==-1):
            return False
        for k in range(len(arr)):
            if(i-k==abs(x-arr[k])):
                return False
        arr.append(x)
    return True
    

def n_queens():
    global board,col
    n=len(board)
    if(verify_output(board)==True):
        print(f'{board}')
    for i in range(n):
        if(board[i][col%n]==0):
            if(check_clash()==False):
                board[i][col%n]=1
                col+=1
                n_queens()
                col-=1
                board[i][col%n]=0
    return


board: 
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]] 


In [6]:
n_queens()

[[1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0.]]
[[1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0.]]
[[0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1.]]
[[0. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0.]]
[[0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1.]]
[[0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0.]]
[[0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0.]]
[[0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]
[[0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0.]]
[[0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0.]]
